apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: school-app
spec:
  capacity:
    storage: 5Gi             # total storage size
  accessModes:
    - ReadWriteOnce          # ek pod at a time read/write kar sakta
